// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prueba_tecnica.Data;

#nullable disable

namespace Prueba_tecnica.Migrations
{
    [DbContext(typeof(PruebaTecnicaDbContext))]
    partial class PruebaTecnicaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prueba_tecnica.Models.Domain.EncuestaCampos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreCampo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Requerido")
                        .HasColumnType("bit");

                    b.Property<string>("TipoCampo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("encuestasEncabezadoIDId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("encuestasEncabezadoIDId");

                    b.ToTable("EncuestaCampos");
                });

            modelBuilder.Entity("Prueba_tecnica.Models.Domain.EncuestasEncabezado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EncuestasEncabezados");
                });

            modelBuilder.Entity("Prueba_tecnica.Models.Domain.EncuestaCampos", b =>
                {
                    b.HasOne("Prueba_tecnica.Models.Domain.EncuestasEncabezado", "encuestasEncabezadoID")
                        .WithMany()
                        .HasForeignKey("encuestasEncabezadoIDId");

                    b.Navigation("encuestasEncabezadoID");
                });
#pragma warning restore 612, 618
        }
    }
}
